/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentacao;

import Modelo.Clima;
import Modelo.Controle;
import Modelo.Estaticos;
import Modelo.Protocolo;
import java.util.ArrayList;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author Rever
 */
public class frmPrincipal extends javax.swing.JDialog
{

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblPrecipitacao = new javax.swing.JLabel();
        lblPrec = new javax.swing.JLabel();
        lblTemperatura = new javax.swing.JLabel();
        lblTemp = new javax.swing.JLabel();
        lblUmidade = new javax.swing.JLabel();
        lblumid = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblConsole = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFerramentas = new javax.swing.JMenu();
        mniHistorico = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("apsMeteorologia");
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        lblPrecipitacao.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblPrecipitacao.setText("Precipitação");

        lblPrec.setText("Precipitação");

        lblTemperatura.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTemperatura.setText("Temperatura");

        lblTemp.setText("Temperatura");

        lblUmidade.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblUmidade.setText("Umidade");

        lblumid.setText("Umidade");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        lblConsole.setForeground(new java.awt.Color(51, 255, 51));
        lblConsole.setText("Sistema");
        lblConsole.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblConsole.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConsole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConsole, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addContainerGap())
        );

        mnuFerramentas.setText("Ferramentas");

        mniHistorico.setText("Historico");
        mniHistorico.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mniHistoricoActionPerformed(evt);
            }
        });
        mnuFerramentas.add(mniHistorico);

        jMenuBar1.add(mnuFerramentas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblumid)
                    .addComponent(lblUmidade)
                    .addComponent(lblPrec)
                    .addComponent(lblPrecipitacao)
                    .addComponent(lblTemp)
                    .addComponent(lblTemperatura))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblumid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUmidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTemp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTemperatura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPrec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPrecipitacao)
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        Controle controle = new Controle();
        Timer timer = new Timer();
        TimerTask task = new TimerTask()
        {
            @Override
            /*Exibir os dados do arduino*/
            public void run()
            {
                lblUmidade.setText(Protocolo.umidade + "%");
                lblTemperatura.setText(Protocolo.temperatura + "ºC");
                lblPrecipitacao.setText(Protocolo.precipitacao + "%");
                lblConsole.setText("<html>" + controle.getMensagem() + "</html>");

            }
        };
        timer.schedule(task, 0, 1000);

        /*Cadastrar*/
        Timer Cadastrar = new Timer();
        TimerTask Loop = new TimerTask()
        {
            @Override
            public void run()
            {
                try
                {
                    List<String> dadosClima = new ArrayList<>();
                    dadosClima.add("0");
                    dadosClima.add(Protocolo.temperatura + "ºC");
                    dadosClima.add(Protocolo.umidade + "%");
                    dadosClima.add(Protocolo.precipitacao + "%");

                    controle.CadastrarClima(dadosClima);
                }
                catch (Exception e)
                {
                    lblConsole.setText("Erro de conexão com o BD");
                }

            }
        };
        Cadastrar.schedule(Loop, 0, 60000);/*Executa a cada 60 segundos*/


    }//GEN-LAST:event_formWindowOpened

    private void mniHistoricoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mniHistoricoActionPerformed
    {//GEN-HEADEREND:event_mniHistoricoActionPerformed
        Controle controle = new Controle();
        List<Clima> listaClima = controle.PesquisarClimaHistorico();

        Estaticos.listaClima = listaClima;
        frmHistorico frmS = new frmHistorico(null, true);
        frmS.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_mniHistoricoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                frmPrincipal dialog = new frmPrincipal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblConsole;
    private javax.swing.JLabel lblPrec;
    private javax.swing.JLabel lblPrecipitacao;
    private javax.swing.JLabel lblTemp;
    private javax.swing.JLabel lblTemperatura;
    private javax.swing.JLabel lblUmidade;
    private javax.swing.JLabel lblumid;
    private javax.swing.JMenuItem mniHistorico;
    private javax.swing.JMenu mnuFerramentas;
    // End of variables declaration//GEN-END:variables
}
